name: cmb-recon
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - astropy
  - healpy
  - ipykernel
  - pip
  - pip:
    - torch
    - torchvision
    - einops
    - tqdm
    - seaborn
    - wandb
    - plotly
